### ISSUE TITLE
Micro python bindings on ubuntu machine

### ISSUE THREAD

**Issue by Riddhikavar** [lvgl/lv_binding_micropython#331] opened 2024-02-13 14:02 UTC
Hi Folks,
 
I am trying to create a GUI application.
 
I want to use python to create GUI, I am working on device rock-pi-4
 
I encountered issues related to micropython bindings, I tried to check examples but getting usys module error, and no solutions for that.
 
I am trying to check this on ubuntu machine before testing it on device.
 
If any one can help me out here. How should I proceed further that will be a great help.
 
Thanks in advance!

**Comment by PGNetHun** [comment] 2024-02-15 09:09
Duplicate of https://github.com/lvgl/lv_binding_micropython/issues/332

**Closed by PGNetHun** 2024-02-15 09:09 UTC
